import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { I18nProvider } from "./i18n";
import BackgroundBlobs from "./components/BackgroundBlobs";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} antialiased`}>
        <I18nProvider>
          <div className="relative min-h-screen">
            <BackgroundBlobs />
            {children}
          </div>
        </I18nProvider>
      </body>
    </html>
  );
}
